name: Deploy Lambda on Push

on:
  push:
    branches:
      - main  # <- You need to change this to YOUR BRANCH. It is probably main but it could be 'master'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2  

      - name: Zip Lambda function code
        run: zip -r function.zip tucker-process-transactions.mjs # <- this needs to be changed to be YOUR .mjs file name. 

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name tucker-process-transactions \ # <- this needs to be YOUR function name as appears in the lambda function list 
